name: CI                      # Покажется на вкладке «Actions»
run-name: >-
  🛠️ ${{ github.actor }} запустил CI для ${{ github.ref_name }}

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:          # ручной запуск из UI
  schedule:
    - cron: '0 4 * * 1'       # еженедельный ночной прогон (понедельник, 04:00 UTC)

# отменяем предыдущие запуски, если есть более свежий коммит в той же ветке
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:                  # минимум прав по умолчанию
  contents: read

jobs:
  # ---------- Линтеры, форматтеры, типизация ----------
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4          # клонируем репозиторий
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # кэшируем скачанные хуки pre-commit
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install --upgrade pre-commit

      - name: Run pre-commit hooks (skip pytest)
        env:
          SKIP: pytest
        run: pre-commit run --all-files --show-diff-on-failure

  # ---------- Юнит-тесты во Frappe / Docker Compose ----------
  tests:
    needs: lint               # выполняем, только если линтеры зелёные
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Build & start bench stack
        run: |
          docker compose -f docker-compose.yml \
            up -d --build --wait --wait-timeout 600

      - name: Run pytest inside backend
        # -T ➜ без TTY — чище логи в CI
        run: docker compose exec -T backend pytest

      # (необязательно) сохраняем отчёты, если их генерируете
      - name: Upload pytest report
        if: always()                                      # даже при падении тестов
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/

      - name: Stop stack
        if: always()
        run: docker compose down -v
