jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & start stack
        run: docker compose -f docker-compose.yml up -d --build --wait --wait-timeout 600

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run tests (inside backend)
        run: docker compose exec -T backend pytest  # -T: без TTY

      - name: Stop stack
        if: always()
        run: docker compose down -v

